export const DOCS_LAST_UPDATED = '2026-03-29';

export const DOCS_OVERVIEW = {
    title: 'Centro de Ayuda Takta',
    summary:
        'Takta conecta activos, ingenieria, ejecucion, calidad, excelencia, actas, documentos y diagramas en una sola operacion guiada por contexto.',
    quickStart: [
        'Inicia sesion y verifica el tenant correcto.',
        'Define activo, SKU o estandar si el flujo depende de contexto.',
        'Empieza por Activos si la estructura aun no existe.',
        'Usa Ingenieria para definir referencias, actividades y estandares.',
        'Captura evidencia en Cronometro, Ejecucion, Muestreo o Actas.',
        'Escala el seguimiento en Excelencia, Documentos o Configuracion.',
    ],
    principles: [
        {
            title: 'Trabaja con contexto',
            body: 'Siempre que sea posible define activo, SKU y estandar antes de entrar a modulos dependientes.',
        },
        {
            title: 'Registra primero, analiza despues',
            body: 'Ejecucion, muestreo, auditorias y actas alimentan decisiones en capacidad, excelencia y seguimiento formal.',
        },
        {
            title: 'Cierra el ciclo',
            body: 'Toda desviacion relevante debe terminar en accion, compromiso, NC/CAPA o documento de soporte.',
        },
    ],
    conventions: [
        'Activo: sede, planta, area, linea, maquina, puesto o componente.',
        'Referencia: SKU o producto atendido por el proceso.',
        'Estandar: combinacion activo + actividad + SKU con tiempo/frecuencia.',
        'Compromiso/accion: actividad con owner, estado y fecha para cerrar una brecha.',
    ],
};

export const DOCS_WORKFLOWS = [
    {
        id: 'wf-standard',
        title: 'Crear un estandar nuevo',
        role: 'Ingenieria de procesos',
        route: '#/engineering',
        modules: ['assets', 'engineering', 'timing'],
        outcome: 'Estandar operativo listo para cronometro, capacidad y muestreo.',
        steps: [
            'Valida el activo en Arbol de Activos.',
            'Registra referencia SKU y actividad tecnica.',
            'Crea el estandar vinculando activo, actividad y referencia.',
            'Si hace falta evidencia, crea un estudio en Cronometro.',
        ],
    },
    {
        id: 'wf-capacity',
        title: 'Resolver una brecha de capacidad',
        role: 'Ingenieria y supervision',
        route: '#/capacity',
        modules: ['engineering', 'capacity', 'excellence'],
        outcome: 'Escenario de staffing y restricciones documentadas.',
        steps: [
            'Confirma que existan estandares activos.',
            'Configura precedencias y restricciones.',
            'Ejecuta calculo de capacidad.',
            'Lleva la decision a Excelencia si requiere accion formal.',
        ],
    },
    {
        id: 'wf-weight-nc',
        title: 'Atender una desviacion de peso',
        role: 'Calidad y operacion',
        route: '#/weight-sampling',
        modules: ['weight-sampling', 'meetings', 'excellence'],
        outcome: 'Desviacion analizada, NC/CAPA creada y seguimiento visible.',
        steps: [
            'Selecciona la especificacion correcta.',
            'Registra las muestras del lote o turno.',
            'Analiza SPC, reglas y capacidad.',
            'Si hay hallazgo, abre NC y luego CAPA.',
        ],
    },
    {
        id: 'wf-shift',
        title: 'Documentar un turno con incidentes',
        role: 'Supervision',
        route: '#/execution',
        modules: ['execution', 'meetings', 'documents'],
        outcome: 'Bitacora del turno con evidencia y acciones de seguimiento.',
        steps: [
            'Registra eventos en Bitacora.',
            'Abre y cierra paros con causa y diagnostico.',
            'Escala acuerdos a Actas IP si hace falta.',
            'Adjunta soporte documental si el cambio lo exige.',
        ],
    },
    {
        id: 'wf-governance',
        title: 'Preparar comite semanal de ingenieria',
        role: 'Lider tecnico',
        route: '#/meetings',
        modules: ['meetings', 'excellence', 'documents'],
        outcome: 'Acta con decisiones, compromisos y evidencia de soporte.',
        steps: [
            'Crea el acta con objetivo, alcance y participantes.',
            'Carga agenda, focos, KPIs y decisiones.',
            'Compara compromisos con la reunion anterior.',
            'Relaciona documentos o issues de calidad abiertos.',
        ],
    },
    {
        id: 'wf-visual',
        title: 'Disenar y simular un layout',
        role: 'Ingenieria visual',
        route: '#/plant-editor',
        modules: ['plant-editor', 'assets', 'capacity'],
        outcome: 'Diagrama o layout listo para analisis de escenarios.',
        steps: [
            'Define los activos involucrados.',
            'Construye el diagrama con capas y conexiones.',
            'Asigna propiedades a nodos y enlaces.',
            'Usa el resultado para decisiones de capacidad o mejora.',
        ],
    },
];

export const DOCS_FAQ = [
    {
        id: 'faq-context',
        question: 'Por que algunos modulos no muestran datos?',
        answer:
            'Los modulos mas tecnicos dependen del contexto actual. Si no has definido activo, SKU o estandar, el listado puede verse vacio o incompleto.',
    },
    {
        id: 'faq-disabled',
        question: 'Que significa "modulo deshabilitado"?',
        answer:
            'El tenant o perfil actual no tiene habilitada esa capacidad mediante feature flags. Debes revisarlo en Configuracion.',
    },
    {
        id: 'faq-imports',
        question: 'Cuando usar XLSX en lugar de captura manual?',
        answer:
            'Usa importacion para cargas masivas o maestros iniciales. Usa captura manual para ajustes puntuales o cuando la validacion depende del contexto actual.',
    },
    {
        id: 'faq-offline',
        question: 'Que hago si estoy offline o la sincronizacion se retrasa?',
        answer:
            'Revisa Configuracion > PWA Offline y Sync Manager. La cola pendiente debe vaciarse cuando regreses a linea.',
    },
];

export const DOC_MODULES = [
    {
        id: 'access',
        title: 'Acceso y Sesion',
        category: 'Plataforma',
        route: '#/login',
        audience: ['Todos', 'Admin'],
        summary: 'Controla autenticacion, sesion activa y bootstrap inicial del tenant antes de entrar a la operacion.',
        whenToUse: 'Usalo cuando necesitas iniciar sesion, validar el tenant correcto, cerrar sesion o resolver problemas de acceso.',
        capabilities: [
            'Iniciar sesion con credenciales vigentes.',
            'Persistir token y validar sesion.',
            'Cerrar sesion y limpiar runtime.',
            'Aplicar branding, menu y configuracion base al entrar.',
        ],
        steps: [
            'Abre la pantalla de login y valida que la marca corresponda al tenant.',
            'Ingresa credenciales y confirma redireccion al dashboard.',
            'Si la sesion ya existe, Takta validara el token antes de cargar la shell.',
            'Cuando termines, cierra sesion para limpiar token y contexto.',
        ],
        outputs: ['Sesion autenticada.', 'Tenant runtime cargado con branding y menu correctos.'],
        integrations: ['landing', 'dashboard', 'settings'],
        entities: [
            {
                id: 'auth-session',
                name: 'Sesion autenticada',
                purpose: 'Estado de usuario validado que habilita rutas privadas.',
                actions: ['Iniciar sesion', 'Validar token', 'Cerrar sesion'],
                fields: ['Usuario', 'Tenant', 'Token', 'Perfil'],
            },
            {
                id: 'tenant-runtime',
                name: 'Runtime del tenant',
                purpose: 'Configuracion en memoria y cache local que aplica white label y menu.',
                actions: ['Cargar runtime', 'Refrescar cache', 'Limpiar al cerrar sesion'],
                fields: ['Brand', 'Logo URL', 'Palette', 'Modules', 'Locale', 'Timezone'],
            },
        ],
        troubleshooting: [
            'Si entras y la marca no coincide, revisa runtime cacheado o el tenant activo.',
            'Si vuelve a login despues de entrar, valida token expirado o fallo de /auth/me.',
        ],
        keywords: 'login acceso sesion auth token tenant runtime brand menu',
    },
    {
        id: 'dashboard',
        title: 'Dashboard',
        category: 'Plataforma',
        route: '#/',
        audience: ['Todos'],
        summary: 'Punto de entrada autenticado para arrancar flujos, revisar accesos rapidos y entrar al resto de modulos.',
        whenToUse: 'Usalo al iniciar la jornada para elegir el flujo correcto o para volver rapidamente a un modulo de trabajo.',
        capabilities: [
            'Entrar a modulos frecuentes desde accesos rapidos.',
            'Ver resumen inicial del entorno.',
            'Usar la barra contextual para navegar y volver.',
        ],
        steps: [
            'Confirma usuario, tenant y branding cargados.',
            'Selecciona el modulo adecuado segun la tarea del dia.',
            'Si el trabajo requiere contexto, define activos o estandares apenas entres al modulo.',
        ],
        outputs: ['Navegacion inicial clara.', 'Arranque rapido de flujos operativos y tecnicos.'],
        integrations: ['assets', 'engineering', 'weight-sampling', 'editor'],
        entities: [
            {
                id: 'dashboard-shortcut',
                name: 'Acceso rapido',
                purpose: 'Tarjeta o enlace que abre un flujo frecuente.',
                actions: ['Abrir modulo', 'Retomar flujo'],
                fields: ['Destino', 'Etiqueta', 'Permiso visible'],
            },
            {
                id: 'route-context-bar',
                name: 'Barra de contexto',
                purpose: 'Cabecera transversal con breadcrumbs, ayuda y acciones relacionadas.',
                actions: ['Volver', 'Abrir acciones rapidas', 'Seguir enlaces relacionados'],
                fields: ['Section', 'Breadcrumbs', 'Help', 'Quick actions', 'Context chips'],
            },
        ],
        troubleshooting: [
            'Si falta un acceso rapido, revisa permisos, feature flags y configuracion UI del tenant.',
        ],
        keywords: 'dashboard inicio quick actions barra contexto breadcrumbs',
    },
    {
        id: 'landing',
        title: 'Landing Publico',
        category: 'Plataforma',
        route: '#/landing',
        audience: ['Invitados', 'Comercial'],
        summary: 'Presenta Takta en modo publico y dirige a login o al centro de ayuda sin requerir sesion.',
        whenToUse: 'Usalo para demostraciones, contexto comercial o acceso guiado antes de autenticarse.',
        capabilities: [
            'Mostrar propuesta general de Takta.',
            'Redirigir a login.',
            'Abrir el centro de ayuda publico.',
        ],
        steps: [
            'Usa la landing para introducir el alcance funcional.',
            'Lleva al usuario a login o a docs segun el objetivo.',
        ],
        outputs: ['Entrada publica ordenada al ecosistema.'],
        integrations: ['access', 'docs'],
        entities: [
            {
                id: 'landing-cta',
                name: 'CTA principal',
                purpose: 'Accion visible para entrar a login o documentacion.',
                actions: ['Ir a login', 'Ir a docs'],
                fields: ['Label', 'Route'],
            },
        ],
        troubleshooting: [
            'Si una ruta publica no abre, revisa router hash y chunks del frontend.',
        ],
        keywords: 'landing publico demo docs login cta',
    },
    {
        id: 'assets',
        title: 'Arbol de Activos',
        category: 'Base',
        route: '#/assets',
        audience: ['Ingenieria', 'Operacion', 'Admin'],
        summary: 'Construye la jerarquia fisica y operativa sobre la que se apoya todo el ecosistema.',
        whenToUse: 'Usalo cuando una planta, linea o maquina aun no existe en Takta o cuando necesitas corregir la estructura padre-hijo.',
        capabilities: [
            'Crear activos raiz y nodos hijos.',
            'Editar detalle de cada activo.',
            'Importar y exportar estructura mediante XLSX.',
            'Usar el activo como contexto canonico.',
        ],
        steps: [
            'Crea primero la estructura macro: sede/planta/area/linea.',
            'Agrega maquinas, puestos y componentes.',
            'Verifica nombres consistentes y tipos correctos.',
            'Exporta el arbol si vas a hacer revision masiva.',
        ],
        outputs: ['Jerarquia operativa estable.', 'Contexto reutilizable en el resto de modulos.'],
        integrations: ['engineering', 'execution', 'documents', 'plant-editor'],
        entities: [
            {
                id: 'asset',
                name: 'Activo',
                purpose: 'Nodo principal de localizacion o equipo.',
                actions: ['Crear activo raiz', 'Crear hijo', 'Editar detalle', 'Eliminar', 'Usar como contexto'],
                fields: ['Nombre', 'Tipo', 'Descripcion', 'Parent_id'],
            },
            {
                id: 'asset-import',
                name: 'Importacion XLSX de activos',
                purpose: 'Carga o actualiza estructuras masivas.',
                actions: ['Descargar plantilla', 'Importar archivo', 'Revisar resumen'],
                fields: ['Archivo .xlsx', 'Jerarquia de padres', 'Tipos de activo'],
            },
        ],
        troubleshooting: [
            'Si un nodo queda huerfano, revisa el parent correcto en la plantilla o en el detalle.',
            'Si otro modulo no reconoce el activo, confirma que el contexto fue aplicado.',
        ],
        keywords: 'activos arbol planta linea maquina puesto componente xlsx import export',
    },
    {
        id: 'engineering',
        title: 'Ingenieria',
        category: 'Core',
        route: '#/engineering',
        audience: ['Ingenieria de procesos'],
        summary: 'Define maestros tecnicos y reglas base del proceso.',
        whenToUse: 'Usalo para registrar referencias, actividades permitidas o estandares operativos.',
        capabilities: [
            'Gestion de referencias SKU.',
            'Gestion de actividades.',
            'Contexto de actividades permitidas por activo.',
            'Creacion y mantenimiento de estandares.',
            'Carga y descarga masiva por XLSX.',
        ],
        steps: [
            'Registra la referencia SKU.',
            'Crea la actividad tecnica.',
            'Asigna actividades permitidas por activo.',
            'Crea el estandar vinculando activo, actividad y SKU.',
        ],
        outputs: ['Base maestra para tiempo, capacidad y calidad.', 'Trazabilidad tecnica del proceso.'],
        integrations: ['timing', 'capacity', 'weight-sampling', 'documents'],
        entities: [
            {
                id: 'product-reference',
                name: 'Referencia SKU',
                purpose: 'Producto o presentacion atendida por el proceso.',
                actions: ['Crear', 'Editar', 'Eliminar', 'Importar/Exportar'],
                fields: ['Codigo', 'Descripcion', 'Familia', 'UOM', 'Packaging UOM'],
            },
            {
                id: 'standard-activity',
                name: 'Actividad',
                purpose: 'Operacion, inspeccion, transporte u otra actividad estandarizada.',
                actions: ['Crear', 'Editar', 'Eliminar'],
                fields: ['Nombre', 'Tipo', 'Is value added'],
            },
            {
                id: 'asset-activity-context',
                name: 'Actividad permitida por activo',
                purpose: 'Restringe que actividades aplican a un activo concreto.',
                actions: ['Asignar', 'Retirar', 'Revisar listado'],
                fields: ['Activo', 'Actividad', 'Origen', 'Activo/inactivo'],
            },
            {
                id: 'process-standard',
                name: 'Estandar',
                purpose: 'Regla tecnica central: activo + actividad + referencia.',
                actions: ['Crear', 'Editar', 'Eliminar', 'Importar/Exportar'],
                fields: ['Activo', 'Actividad', 'Referencia', 'Tiempo estandar', 'Frecuencia', 'Unidad de capacidad'],
            },
        ],
        troubleshooting: [
            'Si Cronometro o Capacidad no muestran opciones, confirma que exista al menos un estandar activo.',
            'Evita duplicar codigos SKU.',
        ],
        keywords: 'ingenieria sku referencia actividad estandar contexto permitida frecuencia uom',
    },
    {
        id: 'timing',
        title: 'Cronometro',
        category: 'Core',
        route: '#/timing',
        audience: ['Ingenieria de procesos'],
        summary: 'Captura evidencia de tiempo real y la convierte en tiempo normal, tiempo estandar y productividad.',
        whenToUse: 'Usalo para validar o recalibrar estandares existentes, o para construir el tiempo base de un proceso nuevo.',
        capabilities: [
            'Crear estudios de tiempo y sesiones.',
            'Registrar elementos y laps por ciclo.',
            'Ejecutar work sampling.',
            'Exportar reporte en MD, CSV o PDF.',
            'Aplicar resultados al estandar.',
        ],
        steps: [
            'Crea el estudio con activo, referencia y configuracion base.',
            'Define los elementos del ciclo.',
            'Inicia la sesion y registra observaciones.',
            'Cierra el estudio, revisa resultados y exporta si hace falta.',
        ],
        outputs: ['Tiempo normal, tiempo estandar y UPH.', 'Reporte formal del estudio.'],
        integrations: ['engineering', 'capacity'],
        entities: [
            {
                id: 'time-study',
                name: 'Estudio de tiempo',
                purpose: 'Contenedor principal de la medicion.',
                actions: ['Crear', 'Abrir detalle', 'Cerrar', 'Eliminar', 'Exportar reporte'],
                fields: ['Nombre', 'Tipo de estudio', 'Activo', 'Referencia', 'Rating', 'Suplementos'],
            },
            {
                id: 'timing-element',
                name: 'Elemento',
                purpose: 'Parte del ciclo que se mide durante el estudio.',
                actions: ['Agregar', 'Ordenar', 'Marcar como ciclico/no ciclico'],
                fields: ['Nombre', 'Tipo', 'Orden', 'Is cyclic'],
            },
            {
                id: 'timing-session',
                name: 'Sesion de captura',
                purpose: 'Jornada de observacion en piso.',
                actions: ['Iniciar', 'Registrar laps', 'Cerrar'],
                fields: ['Started_at', 'Ended_at', 'Notas'],
            },
            {
                id: 'work-sampling',
                name: 'Work Sampling',
                purpose: 'Observaciones puntuales para distribucion de tiempo.',
                actions: ['Registrar observacion', 'Ver resultados'],
                fields: ['Categoria', 'Observed_at', 'Duracion', 'Abnormalidad'],
            },
        ],
        troubleshooting: [
            'Si "Aplicar al estandar" no aparece, revisa que el estudio este ligado a un process_standard_id.',
            'No cierres el estudio sin revisar sesiones abiertas o laps anormales.',
        ],
        keywords: 'cronometro estudio tiempo sampling laps reporte aplicar estandar uph',
    },
    {
        id: 'capacity',
        title: 'Capacidad y Staffing',
        category: 'Core',
        route: '#/capacity',
        audience: ['Ingenieria', 'Lider de operacion'],
        summary: 'Modela restricciones del flujo y calcula capacidad con escenarios de personal.',
        whenToUse: 'Usalo cuando ya exista una base tecnica y necesites identificar cuello de botella o personal requerido.',
        capabilities: [
            'Gestion de precedencias y restricciones.',
            'Calculo de capacidad por activo.',
            'Escenarios de staffing avanzado.',
            'Historico de corridas y supuestos.',
        ],
        steps: [
            'Selecciona el activo o linea objetivo.',
            'Registra dependencias entre estandares.',
            'Corre el calculo de capacidad.',
            'Simula escenarios de staffing y compara historial.',
        ],
        outputs: ['Capacidad disponible por escenario.', 'Recomendacion de personal requerido.'],
        integrations: ['engineering', 'execution', 'excellence'],
        entities: [
            {
                id: 'precedence-dependency',
                name: 'Dependencia de precedencia',
                purpose: 'Representa que un estandar debe ocurrir antes que otro.',
                actions: ['Crear', 'Eliminar', 'Listar'],
                fields: ['Activo', 'Predecessor', 'Successor', 'Min wait', 'Mandatory'],
            },
            {
                id: 'capacity-staffing-history',
                name: 'Escenario de staffing',
                purpose: 'Guarda una corrida avanzada de capacidad/personal.',
                actions: ['Calcular', 'Revisar historico'],
                fields: ['Demand', 'Hours per shift', 'Shifts per day', 'Personnel required', 'Utilization'],
            },
        ],
        troubleshooting: [
            'Si no hay resultados, valida que existan estandares y dependencias coherentes para el activo.',
            'Documenta supuestos de turno y factores mecanicos/manuales.',
        ],
        keywords: 'capacidad staffing precedencia cuello botella utilizacion demanda turno',
    },
    {
        id: 'execution',
        title: 'Ejecucion de Piso',
        category: 'Operacion',
        route: '#/execution',
        audience: ['Supervision', 'Operacion'],
        summary: 'Registra produccion, novedades, personal y configuracion operativa del turno.',
        whenToUse: 'Usalo durante la operacion diaria para dejar bitacora, reportar paros, administrar personal y planificar turnos.',
        capabilities: [
            'Bitacora de produccion.',
            'Gestion de paros y novedades.',
            'Alta de operarios y habilidades.',
            'Asignacion operario-estacion y plan de turnos.',
            'Reglas de contexto y catalogo de fallas.',
        ],
        steps: [
            'Entra al tab correcto: Bitacora, Paros, Personal, Planificacion o Configuracion.',
            'Captura el evento operativo o la novedad.',
            'Completa responsables, activo y diagnostico si aplica.',
            'Usa Personal para mantener skills actualizadas.',
        ],
        outputs: ['Trazabilidad del turno.', 'Datos operativos para mejora y auditoria.'],
        integrations: ['capacity', 'excellence', 'meetings'],
        entities: [
            {
                id: 'production-log',
                name: 'Bitacora de produccion',
                purpose: 'Evento del turno relacionado con produccion.',
                actions: ['Crear evento', 'Consultar timeline', 'Eliminar'],
                fields: ['Activo', 'Shift', 'Event type', 'Event time', 'Quantity', 'Operator'],
            },
            {
                id: 'downtime-event',
                name: 'Paro o novedad',
                purpose: 'Registro de incidente o indisponibilidad.',
                actions: ['Abrir', 'Cerrar', 'Eliminar'],
                fields: ['Activo', 'Tipo', 'Inicio', 'Fin', 'Duracion', 'Root cause', 'Reported by'],
            },
            {
                id: 'operator',
                name: 'Operario',
                purpose: 'Maestro de personal operativo.',
                actions: ['Crear', 'Editar', 'Desactivar'],
                fields: ['Codigo', 'Nombre', 'Area base', 'Turno', 'Fecha de ingreso', 'Restricciones'],
            },
            {
                id: 'operator-skill',
                name: 'Habilidad',
                purpose: 'Relacion operario-actividad y nivel de dominio.',
                actions: ['Asignar', 'Editar', 'Eliminar'],
                fields: ['Operario', 'Actividad', 'Skill level', 'Certified date'],
            },
            {
                id: 'station-assignment',
                name: 'Asignacion operario-estacion',
                purpose: 'Relacion temporal entre operario, activo y turno.',
                actions: ['Asignar', 'Cerrar asignacion'],
                fields: ['Operario', 'Activo', 'Shift', 'Starts at', 'Ends at', 'Status'],
            },
            {
                id: 'shift-plan',
                name: 'Plan de turnos',
                purpose: 'Programacion diaria de personal y objetivo.',
                actions: ['Crear', 'Importar/Exportar', 'Eliminar'],
                fields: ['Plan date', 'Shift', 'Activo', 'Operario', 'Target quantity'],
            },
        ],
        troubleshooting: [
            'Recuerda que #/mobile reutiliza este modulo en modo de campo.',
            'Cierra los paros abiertos: afectan indicadores y seguimiento posterior.',
        ],
        keywords: 'ejecucion bitacora paros operarios skills asignacion plan turnos fallas',
    },
    {
        id: 'mobile',
        title: 'Piso Movil',
        category: 'Operacion',
        route: '#/mobile',
        audience: ['Operacion', 'Supervision'],
        summary: 'Expone el flujo de Ejecucion en un formato mas directo para captura en campo y uso en dispositivos moviles.',
        whenToUse: 'Usalo cuando la operacion necesita registrar eventos desde piso sin pasar por una interfaz mas amplia de escritorio.',
        capabilities: [
            'Registrar novedades y eventos desde campo.',
            'Reusar la misma logica de Ejecucion con menor friccion visual.',
            'Mantener continuidad con el resto del seguimiento operativo.',
        ],
        steps: [
            'Entra desde un dispositivo movil o en una ventana reducida.',
            'Captura evento, paro o novedad con el menor numero de pasos posible.',
            'Sincroniza y luego revisa el detalle completo en Ejecucion si hace falta.',
        ],
        outputs: ['Captura operativa en campo.', 'Datos compatibles con la bitacora principal.'],
        integrations: ['execution', 'meetings', 'excellence'],
        entities: [
            {
                id: 'mobile-capture',
                name: 'Captura movil',
                purpose: 'Entrada rapida de eventos operativos desde campo.',
                actions: ['Crear evento', 'Cerrar paro', 'Sincronizar'],
                fields: ['Activo', 'Shift', 'Tipo', 'Timestamp', 'Observacion'],
            },
        ],
        troubleshooting: [
            'Si la captura queda pendiente, revisa cola offline y conectividad.',
            'Para analisis detallado, abre luego el mismo flujo en Ejecucion de Piso.',
        ],
        keywords: 'mobile piso movil captura campo operacion offline execution',
    },
    {
        id: 'weight-sampling',
        title: 'Muestreo de Peso y Calidad',
        category: 'Calidad',
        route: '#/weight-sampling',
        audience: ['Calidad', 'Operacion', 'Mejora continua'],
        summary: 'Controla variacion del peso, activa SPC, corre capacidad y escala a NC/CAPA.',
        whenToUse: 'Usalo para controlar un proceso con limites de peso y detectar desvio temprano.',
        capabilities: [
            'Alta y edicion de especificaciones.',
            'Captura de muestras.',
            'Analisis SPC y Western Electric.',
            'Ejecucion de capacidad del proceso.',
            'Gestion de no conformidades y CAPA.',
            'Importacion y exportacion XLSX.',
        ],
        steps: [
            'Crea la especificacion con limites y objetivo.',
            'Registra muestras del lote o turno.',
            'Analiza carta de control y reglas.',
            'Si hay hallazgo, crea NC y luego CAPA.',
        ],
        outputs: ['Historia de muestras y desviaciones.', 'Salud estadistica del proceso.', 'NC/CAPA con seguimiento formal.'],
        integrations: ['meetings', 'excellence', 'execution'],
        entities: [
            {
                id: 'weight-spec',
                name: 'Especificacion de peso',
                purpose: 'Define limites y objetivo del proceso.',
                actions: ['Crear', 'Editar', 'Eliminar', 'Importar/Exportar'],
                fields: ['Nombre', 'Activo', 'Referencia', 'Unidad', 'Lower limit', 'Target', 'Upper limit', 'Sample size'],
            },
            {
                id: 'weight-sample',
                name: 'Muestra de peso',
                purpose: 'Dato crudo medido en proceso.',
                actions: ['Registrar', 'Editar', 'Eliminar'],
                fields: ['Measured value', 'Measured at', 'Measured by', 'Batch code', 'Shift', 'Deviation'],
            },
            {
                id: 'weight-capability',
                name: 'Corrida de capacidad',
                purpose: 'Evalua Cp, Cpk, Pp y Ppk del proceso.',
                actions: ['Ejecutar', 'Revisar tendencia'],
                fields: ['Window', 'Sample count', 'Cp', 'Cpk', 'Capability status', 'Alert level'],
            },
            {
                id: 'non-conformity',
                name: 'No conformidad',
                purpose: 'Registro formal de hallazgo o desviacion.',
                actions: ['Crear', 'Editar estado', 'Aprobar/cerrar', 'Eliminar'],
                fields: ['Severity', 'Status', 'Title', 'Description', 'Root cause', 'Containment'],
            },
            {
                id: 'capa-action',
                name: 'Accion CAPA',
                purpose: 'Accion correctiva o preventiva asociada a una NC.',
                actions: ['Crear', 'Editar', 'Cerrar', 'Eliminar'],
                fields: ['Action type', 'Title', 'Responsible', 'Due date', 'Status', 'Verification notes'],
            },
        ],
        troubleshooting: [
            'Si no ves SPC util, valida que exista cantidad suficiente de muestras.',
            'Relaciona activo, SKU y proceso para mejorar filtros y seguimiento.',
        ],
        keywords: 'peso muestreo spc cpk capa no conformidad capacidad western electric',
    },
    {
        id: 'excellence',
        title: 'Excelencia Operacional',
        category: 'Mejora',
        route: '#/excellence',
        audience: ['Mejora continua', 'Jefaturas', 'Calidad'],
        summary: 'Concentra acciones, auditorias, KPI MC, Kanban y VSM para gobernar la mejora continua.',
        whenToUse: 'Usalo cuando una desviacion o iniciativa ya requiere seguimiento transversal, scorecard, auditoria o rediseño del flujo.',
        capabilities: [
            'Action Tracker con workflow.',
            'Auditorias avanzadas 5S y templates.',
            'Scorecard y tendencia KPI MC.',
            'Calculo de Kanban.',
            'Lienzos VSM.',
        ],
        steps: [
            'Selecciona el tab adecuado: Actions, Auditorias 5S, KPI MC, Kanban o VSM.',
            'Registra la accion o medicion con owner y fecha.',
            'Monitorea workflow, scorecard o resultado del calculo.',
            'Conecta con Actas IP cuando la revision ocurra en comite.',
        ],
        outputs: ['Backlog y workflow formal de acciones.', 'Indicadores MC consolidados.', 'Analisis de flujo y abastecimiento.'],
        integrations: ['meetings', 'weight-sampling', 'capacity', 'documents'],
        entities: [
            {
                id: 'improvement-action',
                name: 'Accion de mejora',
                purpose: 'Item central de seguimiento para brechas o iniciativas.',
                actions: ['Crear', 'Editar', 'Eliminar', 'Exportar tablero'],
                fields: ['Source document', 'Description', 'Responsible', 'Due date', 'Status'],
            },
            {
                id: 'action-workflow',
                name: 'Workflow de accion',
                purpose: 'Aprobacion o verificacion del cierre.',
                actions: ['Solicitar cierre', 'Aprobar', 'Verificar'],
                fields: ['Workflow status', 'Requested by', 'Approved by', 'Verified by', 'Evidence'],
            },
            {
                id: 'audit-instance',
                name: 'Auditoria 5S',
                purpose: 'Resultado de una auditoria o checklist.',
                actions: ['Crear auditoria', 'Comparar radar', 'Eliminar'],
                fields: ['Activo', 'Type', 'Auditor', 'Audit date', 'Total score'],
            },
            {
                id: 'audit-checklist-template',
                name: 'Template de checklist',
                purpose: 'Plantilla reutilizable para auditorias.',
                actions: ['Crear', 'Editar', 'Activar/desactivar'],
                fields: ['Name', 'Type', 'Require photo', 'Items'],
            },
            {
                id: 'mc-kpi-definition',
                name: 'Definicion KPI MC',
                purpose: 'Catalogo canonico de indicadores de mejoramiento continuo.',
                actions: ['Editar catalogo', 'Asignar pesos'],
                fields: ['Code', 'Focus area', 'Action line', 'Indicator name', 'Kpi weight'],
            },
            {
                id: 'mc-kpi-measurement',
                name: 'Medicion KPI MC',
                purpose: 'Captura periodica del indicador.',
                actions: ['Upsert por periodo', 'Consultar scorecard', 'Eliminar medicion'],
                fields: ['Period', 'Target', 'Actual', 'Compliance pct', 'Status color'],
            },
            {
                id: 'kanban-loop',
                name: 'Loop Kanban',
                purpose: 'Calculo de tarjetas y contenedores entre origen y destino.',
                actions: ['Calcular', 'Consultar loops'],
                fields: ['SKU', 'Asset origin', 'Asset dest', 'Container capacity', 'Daily demand', 'Lead time'],
            },
            {
                id: 'vsm-canvas',
                name: 'Canvas VSM',
                purpose: 'Mapa de flujo de valor con nodos y enlaces.',
                actions: ['Crear', 'Editar', 'Eliminar'],
                fields: ['Name', 'Asset', 'Nodes', 'Edges', 'Constraints'],
            },
        ],
        troubleshooting: [
            'Si una accion no cambia de workflow, valida permisos y estado previo.',
            'No mezcles KPI sin periodo valido.',
        ],
        keywords: 'excelencia mejora accion workflow auditoria 5s kpi mc kanban vsm',
    },
    {
        id: 'meetings',
        title: 'Actas IP',
        category: 'Gobernanza',
        route: '#/meetings',
        audience: ['Comites tecnicos', 'Lideres'],
        summary: 'Estructura reuniones tecnicas, compromisos y seguimiento entre semanas.',
        whenToUse: 'Usalo cuando la decision o seguimiento requiere una sesion formal con participantes, agenda, focos, KPIs y compromisos.',
        capabilities: [
            'Crear y editar actas.',
            'Comparativo intersemanal.',
            'Materializacion de compromisos en acciones.',
            'Sincronizacion con issues de calidad.',
            'Importacion heuristica desde texto.',
        ],
        steps: [
            'Crea el acta con fecha, estado y objetivo.',
            'Registra participantes, agenda, focos y compromisos.',
            'Consulta comparativo con la reunion anterior.',
            'Sincroniza compromisos con calidad o materializalos en acciones.',
        ],
        outputs: ['Acta auditable.', 'Compromisos abiertos/cerrados/vencidos.', 'Conexion explicita con NC/CAPA y mejora.'],
        integrations: ['excellence', 'weight-sampling', 'documents'],
        entities: [
            {
                id: 'engineering-meeting',
                name: 'Acta',
                purpose: 'Registro principal de una sesion de ingenieria.',
                actions: ['Crear', 'Editar', 'Eliminar', 'Comparar'],
                fields: ['Title', 'Meeting date', 'Objective', 'Scope', 'Risks', 'Next meeting date', 'Status'],
            },
            {
                id: 'meeting-participant',
                name: 'Participante',
                purpose: 'Persona convocada o asistente.',
                actions: ['Agregar', 'Editar asistencia'],
                fields: ['Name', 'Role', 'Attendance'],
            },
            {
                id: 'meeting-commitment',
                name: 'Compromiso',
                purpose: 'Acuerdo accionable de la reunion.',
                actions: ['Agregar', 'Cambiar estado', 'Materializar accion'],
                fields: ['Description', 'Responsible', 'Due date', 'Status', 'Asset', 'Action id'],
            },
            {
                id: 'meeting-quality-sync',
                name: 'Sincronizacion calidad',
                purpose: 'Trae issues NC/CAPA al contexto del comite.',
                actions: ['Consultar issues', 'Sincronizar compromisos'],
                fields: ['Meeting id', 'Created commitments', 'Linked existing', 'Total commitments'],
            },
        ],
        troubleshooting: [
            'Evita editar JSON del acta fuera de la app.',
            'No dejes compromisos sin responsable ni fecha si vas a hacer seguimiento.',
        ],
        keywords: 'actas reuniones compromisos comparacion calidad sync comite heuristic import',
    },
    {
        id: 'documents',
        title: 'Documentos',
        category: 'Conocimiento',
        route: '#/documents',
        audience: ['Ingenieria', 'Calidad', 'Documentacion'],
        summary: 'Consulta, filtra y da seguimiento al repositorio de documentos tecnicos generados en Takta.',
        whenToUse: 'Usalo cuando necesitas revisar historial documental o validar que un archivo fue creado.',
        capabilities: [
            'Listar documentos creados.',
            'Filtrar por plantilla, activo, autor y contexto.',
            'Abrir render o detalle.',
            'Eliminar o mantener trazabilidad documental.',
        ],
        steps: [
            'Abre el listado y aplica filtros si buscas un documento especifico.',
            'Usa el contexto actual para encontrar documentos relacionados.',
            'Abre el documento para revisar contenido renderizado.',
        ],
        outputs: ['Repositorio navegable de documentos y evidencia tecnica.'],
        integrations: ['editor', 'assets', 'meetings'],
        entities: [
            {
                id: 'format-template',
                name: 'Template documental',
                purpose: 'Estructura base usada por el editor.',
                actions: ['Consultar catalogo', 'Ingerir templates'],
                fields: ['Code', 'Name', 'Category', 'Markdown structure'],
            },
            {
                id: 'format-instance',
                name: 'Documento creado',
                purpose: 'Instancia final generada desde una plantilla.',
                actions: ['Listar', 'Abrir', 'Eliminar'],
                fields: ['Template', 'Asset', 'User', 'Created_at', 'Updated_at', 'Content'],
            },
        ],
        troubleshooting: [
            'Si el documento no aparece en el listado, revisa que haya sido guardado y no solo autosave.',
            'Mantener el contexto correcto facilita recuperar documentos luego.',
        ],
        keywords: 'documentos repositorio plantillas filtro render historial',
    },
    {
        id: 'editor',
        title: 'Editor Docs',
        category: 'Conocimiento',
        route: '#/editor',
        audience: ['Ingenieria', 'Calidad', 'Documentacion'],
        summary: 'Crea documentos tecnicos estructurados a partir de templates.',
        whenToUse: 'Usalo cuando necesitas formalizar instrucciones, SOP, actas tecnicas o documentos estandar.',
        capabilities: [
            'Crear documento desde template.',
            'Autosave y guardado formal.',
            'Vinculo de contexto con activo, SKU o estandar.',
            'Exportacion o render documental segun flujo.',
        ],
        steps: [
            'Selecciona la plantilla correcta.',
            'Completa el contenido tecnico y relaciona contexto si aplica.',
            'Guarda el documento y valida su aparicion en Documentos.',
        ],
        outputs: ['Documento estructurado y trazable.'],
        integrations: ['documents', 'assets', 'meetings'],
        entities: [
            {
                id: 'document-editor-session',
                name: 'Sesion de edicion',
                purpose: 'Trabajo en curso sobre una instancia documental.',
                actions: ['Crear', 'Autosave', 'Guardar formal'],
                fields: ['Template', 'User', 'Source context', 'Content blocks'],
            },
        ],
        troubleshooting: [
            'Si el contenido no persiste, valida conectividad o revisa la cola offline.',
            'Define el template correcto antes de redactar.',
        ],
        keywords: 'editor docs autosave template documento save render',
    },
    {
        id: 'plant-editor',
        title: 'Diagram Studio',
        category: 'Visual',
        route: '#/plant-editor',
        audience: ['Ingenieria visual', 'Mejora'],
        summary: 'Modela layouts, diagramas y escenarios visuales con estructura por capas.',
        whenToUse: 'Usalo para representar una planta, flujo o layout y analizar decisiones visuales o de simulacion.',
        capabilities: [
            'Crear y editar layouts/diagramas.',
            'Gestionar capas y estructura padre-hijo.',
            'Usar libreria de elementos y propiedades.',
            'Preparar escenarios para simulacion.',
        ],
        steps: [
            'Crea o abre un layout existente.',
            'Agrega elementos, organiza capas y conecta nodos.',
            'Asigna propiedades relevantes y guarda el diagrama.',
            'Si aplica, usa escenarios de simulacion.',
        ],
        outputs: ['Layout o diagrama guardado con trazabilidad.'],
        integrations: ['assets', 'capacity', 'documents'],
        entities: [
            {
                id: 'plant-layout',
                name: 'Layout o diagrama',
                purpose: 'Archivo principal del editor visual.',
                actions: ['Crear', 'Guardar', 'Actualizar', 'Eliminar'],
                fields: ['Name', 'Asset', 'Json content', 'Thumbnail', 'Active'],
            },
            {
                id: 'diagram-library-item',
                name: 'Elemento de libreria',
                purpose: 'Objeto reutilizable para construir diagramas.',
                actions: ['Consultar', 'Marcar favorito'],
                fields: ['Domain', 'Code', 'Name', 'Element type', 'Version'],
            },
            {
                id: 'simulation-scenario',
                name: 'Escenario de simulacion',
                purpose: 'Configuracion de una corrida ligada al layout.',
                actions: ['Crear', 'Ejecutar', 'Comparar resultados'],
                fields: ['Name', 'Asset', 'Diagram', 'Mode', 'Config'],
            },
        ],
        troubleshooting: [
            'Si un diagrama no representa bien la planta, confirma primero la base de activos.',
            'Nombra capas y objetos con criterio.',
        ],
        keywords: 'diagram studio layout planta simulacion capas libreria escenario',
    },
    {
        id: 'settings',
        title: 'Configuracion',
        category: 'Plataforma',
        route: '#/settings',
        audience: ['Admin de plataforma'],
        summary: 'Administra sesion, navegacion, branding, integracion y salud operativa de la plataforma.',
        whenToUse: 'Usalo para tareas de administracion del tenant, soporte, observabilidad o mantenimiento operacional.',
        capabilities: [
            'Revisar sesion y tenant actual.',
            'Administrar navegacion y plantillas base.',
            'Gestionar white label y feature flags.',
            'Monitorear salud de integracion.',
            'Consultar catalogo de eventos.',
            'Operar PWA y cola offline.',
        ],
        steps: [
            'Verifica primero tenant y perfil actual.',
            'Ajusta branding y flags con cuidado.',
            'Consulta salud de integracion y eventos si hay fallas.',
            'Gestiona offline queue cuando trabajes con PWA.',
        ],
        outputs: ['Tenant ajustado, observabilidad disponible y soporte operativo del entorno.'],
        integrations: ['all'],
        entities: [
            {
                id: 'tenant-theme',
                name: 'Tema del tenant',
                purpose: 'Branding visible de la app.',
                actions: ['Editar marca', 'Cambiar paleta', 'Definir logo'],
                fields: ['Brand name', 'Badge label', 'Logo URL', 'Colors', 'Typography', 'Custom CSS'],
            },
            {
                id: 'tenant-ui-config',
                name: 'Configuracion UI',
                purpose: 'Menu y modulos visibles por tenant.',
                actions: ['Editar menu', 'Ajustar locale/timezone'],
                fields: ['Menu', 'Modules', 'Locale', 'Timezone'],
            },
            {
                id: 'tenant-feature-flag',
                name: 'Feature flag',
                purpose: 'Habilita o deshabilita capacidades de la plataforma.',
                actions: ['Activar', 'Desactivar', 'Cambiar rollout'],
                fields: ['Feature key', 'Is enabled', 'Rollout', 'Notes'],
            },
            {
                id: 'integration-event',
                name: 'Evento de integracion',
                purpose: 'Registro de observabilidad para procesos y conectores.',
                actions: ['Consultar catalogo', 'Filtrar por severidad o modulo'],
                fields: ['Module', 'Event code', 'Severity', 'Status', 'Entity type', 'Payload'],
            },
            {
                id: 'integration-health',
                name: 'Snapshot de salud',
                purpose: 'Resumen del estado de integracion del tenant.',
                actions: ['Consultar ultimo snapshot', 'Revisar warning/critical'],
                fields: ['Status', 'Orphan count', 'Mismatch count', 'Summary'],
            },
            {
                id: 'offline-queue',
                name: 'Cola offline',
                purpose: 'Operaciones pendientes mientras no hay conectividad.',
                actions: ['Revisar pendientes', 'Reintentar sincronizacion', 'Resolver conflictos'],
                fields: ['Pending jobs', 'Sync state', 'Conflicts'],
            },
        ],
        troubleshooting: [
            'Si un modulo desaparece del menu, revisa feature flags antes de asumir error de frontend.',
            'Si el branding se ve mal, valida runtime cacheado y configuracion persistida del tenant.',
        ],
        keywords: 'configuracion tenant white label feature flag integration health offline pwa menu',
    },
];

export const DOCS_MODULES = DOC_MODULES;
